version: '3.9'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_MULTIPLE_DATABASES: dev,test
    volumes:
      - ./db/scripts/multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
